spring:
  application:
    name: workflow-management-system


  datasource:
    url: jdbc:mysql://localhost:3306/workflow_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: workflow_user
    password: workflow_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # ===== CONFIGURATION KEYCLOAK OAUTH2 =====
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/workflow-realm

# ===== CONFIGURATION SERVEUR =====
server:
  port: 8081
  servlet:
    context-path: /

# ===== CONFIGURATION LOGGING =====
logging:
  level:
    root: INFO
    ma.xproce.workflow: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG